# Generated by Django 4.1.3 on 2022-12-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GestionFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreFuncionario', models.CharField(max_length=20)),
                ('apellidoFuncionario', models.CharField(max_length=20)),
                ('rutFuncionario', models.CharField(max_length=15)),
                ('telefonoFuncionario', models.CharField(max_length=10)),
                ('direccionFuncionario', models.CharField(max_length=200)),
                ('contactoEmergencia', models.CharField(max_length=20)),
                ('telefonoEmergencia', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GestionInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=20)),
                ('cantidadProducto', models.CharField(max_length=20)),
                ('fechaCompra', models.DateField()),
                ('nombreProveedor', models.CharField(max_length=10)),
                ('telefonoProveedor', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GestionReservaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(max_length=20)),
                ('apellidoCliente', models.CharField(max_length=20)),
                ('rutCliente', models.CharField(max_length=15)),
                ('telefonoCliente', models.CharField(max_length=10)),
                ('direccionCliente', models.CharField(max_length=200)),
                ('fechaReserva', models.DateField()),
                ('horaReserva', models.TimeField()),
                ('mascotaCliente', models.CharField(max_length=20)),
            ],
        ),
    ]
