# Generated by Django 4.1.3 on 2022-12-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petvalpo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
